### ISSUE TITLE
Not a big issue but

### ISSUE THREAD

**Issue by s9e6dy** [GregoryConrad/WirelessEMP#1]
Could you tell me exactly how to use this, I'm new to Linux and I have no idea how to use this, I've installed it and all that but I'm just clueless lol. If you made an in depth tutorial that'd be sick

**Comment by GregoryConrad** [comment]
No clue if the script will even work nowadays; it is pretty ancient and I don't even remember making it (I think I was 14 when I made it...) 

After you have all dependencies installed (should be good to go if you are running in Kali linux), you can get help by running the script with no arguments, like:
```bash
# as root:
bash wemp.sh
```
